theme: minima
title: WinEFIMounter
name: franzageek
description: Mount your Hackintosh EFI from Windows
header_pages:
  - topbar/introduction.md
  - topbar/usage.md
  - topbar/errors.md
  - topbar/credits.md
  - topbar/downloads.md
 
