name: GCC Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y build-essential

    - name: Compile
      run: |
        mkdir -p build
        g++ src/*.cxx -o bin/WinEFIMounter.exe -Os -std=c++23 --static -Wall -Wextra -pedantic
